This program goes through the excel spreadsheet and calculates age ranges and occupation frequencies.

In [11]:
from openpyxl import load_workbook
import datetime

def calc_age(date):
    
    if date == 'None':
        # Empty cell ignore it
        return -1
    today = datetime.datetime.now()
    today_date = datetime.date(today.year, today.month, today.day)
    dob = datetime.date(int(date[:4]), int(date[5:7]), int(date[8:10]))
    
    return ((today_date - dob) / 365).days


wb = load_workbook('KPMG_Raw_Data.xlsx')
wb.active = 3
sheet = wb.active

ten_to_15 = 0
sixteen_to_20 = 0
twenty1_to_25 = 0
twenty6_to_30 = 0
thirty1_to_35 = 0
thirty6_to_40 = 0
fourty1_to_45 = 0
fourty6_to_50 = 0
fifty1_to_55 = 0
fifty6_to_60 = 0
sixty1_to_65 = 0
sixty6_to_70= 0
seventy_plus = 0

for i in range(1, 1874):
    # i = cur row
    
    age = calc_age(str(sheet.cell(row=i, column=6).value))
    
    if 15 >= age >= 10:
        ten_to_15 += 1
    elif 20 >= age >= 16:
        sixteen_to_20 += 1
    elif 25 >= age >= 21:
        twenty1_to_25 += 1
    elif 30 >= age >= 26:
        twenty6_to_30 += 1
    elif 35 >= age >= 31:
        thirty1_to_35 += 1
    elif 40 >= age >= 36:
        thirty6_to_40 += 1
    elif 45 >= age >= 41:
        fourty1_to_45 += 1
    elif 50 >= age >= 46:
        fourty6_to_50 += 1
    elif 55 >= age >= 51:
        fifty1_to_55 += 1
    elif 60 >= age >= 56:
        fifty6_to_60 += 1
    elif 65 >= age >= 61:
        sixty1_to_65 += 1
    elif 70 >= age >= 66:
        sixty6_to_70 += 1
    elif age > 70:
        seventy_plus += 1

print('10-15: ' + str(ten_to_15))
print('16-20: ' + str(sixteen_to_20))
print('21-25: ' + str(twenty1_to_25))
print('26-30: ' + str(twenty6_to_30))
print('31-35: ' + str(thirty1_to_35))
print('36-40: ' + str(thirty6_to_40))
print('41-45: ' + str(fourty1_to_45))
print('46-50: ' + str(fourty6_to_50))
print('51-55: ' + str(fifty1_to_55))
print('56-60: ' + str(fifty6_to_60))
print('61-65: ' + str(sixty1_to_65))
print('66-70: ' + str(sixty6_to_70))
print('70+: ' + str(seventy_plus))

10-15: 0
16-20: 56
21-25: 179
26-30: 141
31-35: 188
36-40: 168
41-45: 400
46-50: 221
51-55: 162
56-60: 174
61-65: 155
66-70: 27
70+: 1

In [14]:
# This part goes through and finds frequency of all occupations

occupations = {}

for i in range(1,1874):
    
    occupation = str(sheet.cell(row=i, column=7).value)
    if occupation in occupations:
        occupations[occupation] += 1
    else:
        occupations[occupation] = 0

for job in occupations:
    print(job + " " + str(occupations[job]))

Associate Professor 25
Technical Writer 24
Staff Accountant II 6
Clinical Specialist 15
Quality Control Specialist 11
Account Coordinator 18
Food Chemist 16
Information Systems Manager 18
Desktop Support Technician 21
Director of Sales 15
Administrative Officer 16
Senior Developer 19
Senior Quality Engineer 12
Structural Engineer 20
Dental Hygienist 20
Sales Representative 23
Account Executive 14
Community Outreach Specialist 16
Operator 10
Accounting Assistant IV 4
Financial Analyst 10
Paralegal 17
Assistant Professor 16
Staff Accountant III 4
Legal Assistant 19
Geological Engineer 14
Accounting Assistant III 3
Social Worker 21
Professor 15
Compensation Analyst 15
Environmental Tech 9
Internal Auditor 16
Teacher 15
Speech Pathologist 17
Sales Associate 15
Accountant IV 7
Health Coach IV 6
VP Accounting 10
Geologist I 1
Project Manager 10
Data Coordiator 8
Administrative Assistant IV 7
Graphic Designer 17
Nurse Practicioner 15
Budget/Accounting Analyst I 4
Registered Nurse 18
Geologist III 3
Programmer I 3
Help Desk Operator 12
Office Assistant I 6
Senior Cost Accountant 15
Librarian 17
Senior Sales Associate 12
Web Developer III 5
Civil Engineer 11
Media Manager IV 4
Cost Accountant 20
Geologist IV 3
Assistant Media Planner 19
Junior Executive 18
Mechanical Systems Engineer 11
Senior Financial Analyst 16
Health Coach III 1
Occupational Therapist 10
Engineer II 2
Software Consultant 11
Research Assistant II 4
Recruiter 15
Systems Administrator II 2
VP Product Management 13
Tax Accountant 23
Administrative Assistant I 2
Biostatistician IV 6
Automation Specialist I 4
Software Engineer IV 1
Actuary 12
Accountant I 4
Pharmacist 13
GIS Technical Architect 19
Administrative Assistant III 4
Executive Secretary 18
Account Representative IV 4
Analog Circuit Design manager 13
Budget/Accounting Analyst IV 6
Electrical Engineer 14
Nuclear Power Engineer 17
Product Engineer 22
Budget/Accounting Analyst II 4
Programmer II 3
Web Designer IV 5
Software Test Engineer I 4
Software Engineer II 4
Web Developer IV 3
VP Quality Control 16
Safety Technician III 5
Chemical Engineer 18
Editor 9
Programmer Analyst III 5
Financial Advisor 8
Research Nurse 13
Business Systems Development Analyst 26
Staff Scientist 20
Recruiting Manager 17
General Manager 20
Senior Editor 14
Biostatistician II 6
Account Representative II 3
Research Associate 13
Marketing Manager 15
Office Assistant III 2
Assistant Manager 11
Help Desk Technician 13
Account Representative I 6
Nurse 19
Analyst Programmer 10
Automation Specialist III 3
Developer III 3
Safety Technician II 6
VP Sales 14
Systems Administrator I 3
Computer Systems Analyst II 7
Accountant III 6
Quality Engineer 12
Safety Technician I 2
Programmer Analyst II 3
Programmer III 3
Software Test Engineer II 6
Systems Administrator III 2
Geologist II 2
Web Developer II 2
Health Coach II 3
Payment Adjustment Coordinator 11
Environmental Specialist 18
Physical Therapy Assistant 17
Biostatistician I 3
Web Designer III 2
Computer Systems Analyst I 6
Web Developer I 2
Accounting Assistant II 2
Automation Specialist II 3
Statistician III 2
Staff Accountant IV 2
Health Coach I 1
VP Marketing 14
Database Administrator I 0
Statistician II 8
Computer Systems Analyst III 1
Human Resources Assistant IV 2
Office Assistant II 2
Safety Technician IV 0
Structural Analysis Engineer 12
Software Test Engineer IV 1
Human Resources Assistant III 5
Accounting Assistant I 4
Web Designer I 6
Human Resources Manager 6
Accountant II 5
Office Assistant IV 3
Engineer IV 5
Engineer I 2
Database Administrator III 5
Chief Design Engineer 16
Programmer Analyst IV 2
Human Resources Assistant II 3
Media Manager I 2
Programmer Analyst I 5
Budget/Accounting Analyst III 2
Software Test Engineer III 4
Software Engineer I 3
Human Resources Assistant I 2
Database Administrator IV 4
Computer Systems Analyst IV 4
Biostatistician III 1
Web Designer II 3
Research Assistant IV 2
Developer II 4
Design Engineer 6
Marketing Assistant 5
Software Engineer III 5
None 10
Developer IV 2
Media Manager II 2
Engineer III 3
Systems Administrator IV 3
Statistician I 2
Staff Accountant I 2
Media Manager III 3
Research Assistant I 2
Research Assistant III 2
Statistician IV 3
Administrative Assistant II 0
Programmer IV 2
Account Representative III 2
Automation Specialist IV 2